// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rplxgzkifbszwhxmedud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwbHhnemtpZmJzendoeG1lZHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzM3ODEsImV4cCI6MjA3MjQwOTc4MX0.EFg4xvV43kDgGoujpj5rtFuux4E2gGwdMHna0lql5kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});